### ISSUE TITLE
Template:Creature_mutation is broken

### ISSUE THREAD

**Issue by kernelmethod** [TrashMonks/wiki-issue-tracker#2]
The `Template:Creature_mutation` template is currently reporting an error:

```
Lua error in Module:Creature_Mutation_Query at line 84: attempt to concatenate local 'level' (a nil value).

Backtrace:

    (tail call): ?
    [Module:Creature_Mutation_Query:84](https://wiki.cavesofqud.com/index.php?title=Module:Creature_Mutation_Query&action=edit#mw-ce-l84): ?
    (tail call): ?
    mw.lua:525: ?
    (tail call): ?
    [C]: in function "xpcall"
    MWServer.lua:99: in function "handleCall"
    MWServer.lua:313: in function "dispatch"
    MWServer.lua:52: in function "execute"
    mw_main.lua:7: in main chunk
    [C]: ?
```

https://wiki.cavesofqud.com/wiki/Template:Creature_mutation

A downstream effect of this error is that creatures aren't having their ego mod added to their mutation levels. For example, the Dervish of the Sightless Way's Teleportation level is shown as level -2:

https://wiki.cavesofqud.com/wiki/Dervish_of_the_Sightless_Way

**Comment by Wreckstation** [comment]
Fixed now. i'm not sure how it functioned in the first place with this error ???
